spring:
  application:
    name: yshu-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: b1baf82eb5f2a3870a515698e894b1be2b4d0e999a81a43cac5d6ed172660fc90b8d37d0599a42c2868c0a823f21f177ac90e64fb75d54ad7508cb73434af7d280f5a9fdf2f295f61d8ecb69a65de0f8769beb032f4d46020e7c606454c05701824786e5944ede4021efcddddac9050fc5c7ec018c7f3f490cfe0c04bcb0d0da5bf838e07ff102a01952cf398ba668ff
    username: devuser
    password: devNEQvE
  redis:
    host: 47.101.214.41
    password: redis@ys
    port: 6379
    timeout: 3000
    database: 0
mybatis:
  mapper-locations: classpath:com/yshu/order/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.yshu.order.*.* : DEBUG
ribbon:
  eureka:
    enabled: true
    ReadTimeout: 1400000
    ConnectTimeout: 300000
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
test:
  value: qiirjjfdf
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9900/eureka/
server:
  port: 9920
