spring:
  application:
    name: yshu-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.101.214.41:3306/springboot_test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: devuser
    password: '{cipher}6a06c4b392f78383644be3c74357963b4806e4c04cf9d6c0792ab55f819e5f42'
  redis:
    host: 47.101.214.41
    password: redis@ys
    port: 6379
    timeout: 3000
    database: 0
mybatis:
  mapper-locations: classpath:com/yshu/order/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.yshu.order.*.* : DEBUG
ribbon:
  eureka:
    enabled: true
    ReadTimeout: 1400000
    ConnectTimeout: 300000
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
test:
  value: qiirjjfdf
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9900/eureka/
server:
  port: 9920
