spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.101.214.41:3306/springboot_test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: devuser
    password: devNEQvE
  redis:
    host: 47.101.214.41
    password: redis@ys
    port: 6379
    timeout: 3000
    database: 0
mybatis:
  mapper-locations: classpath:com/yshu/order/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.yshu.order.*.* : DEBUG
ribbon:
  eureka:
    enabled: true
    ReadTimeout: 1400000
    ConnectTimeout: 300000
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true

