feign:
  httpclient:
    enabled: true
  hystrix:
    enabled: true
logging:
  level:
    com:
      yshu:
        order:
          '*':
            '*': DEBUG
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/yshu/order/mapper/*.xml
ribbon:
  eureka:
    ConnectTimeout: 300000
    ReadTimeout: 1400000
    enabled: true
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: devNEQvE
    url: jdbc:mysql://47.101.214.41:3306/springboot_test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: devuser
  redis:
    database: 0
    host: 47.101.214.41
    password: redis@ys
    port: 6379
    timeout: 3000
